travis:
  secure:
    BINSTAR_TOKEN: q4KO32/lmFCuMkUxqnc98GzEfEfIvBo3pPJVUXnspwFOohyRTO4pcE+GL5eyQiUIW1DTx9qJYSedw1xp5yIYsfOKbmyIlLSXavNjBBRAuLiixRyptRGgK2M843lm006XHHSDoYGqgCwVuCmxkHIuJmmgNrAvIK95IB8tagKWijznA83HP1MzW2RUBOqhgnAVA8XJ0gIlPV43JvwyoRQnAUbulTQU5bNXtm5iWXYrsAKS8VBDprub28TM0EkUPmYeBRk+/twskQmGX2thRJ07xr9qvqZCYzUfCKenaI974g3JcCJ3yAqLWyeBfe4ZJXPtqVtgqh2sxfoRfWcL2P65UQUPJR9yRrtt2h1JMxcaXkstOONSfBeWtD8swweTIV3aMrZ2D0kQg16C1HdtvysFsE420ombBAdBbJIKdkx6WkaAVrUWkTmxmKF37fzSyFXEp8pchMZFtYpVHOn3hfviKbO7iPhpCODnuaJ5ImmLUc0HCYmHcwhY/QDRycRD86f6roPB+d0iSfsTT58jXjNZtvHH8oBVjqTgalFOZ8b3wWHZiqbbhbMTT624a/Pmso5lQuUJ+Z8a3hTq3NJDkb0bSot71dmgYTs0HKXvJXEbhwC1/57ouVEDaDD/54wBoaVQCqI5onyoRoVSBsZCBR9RjGClRa7zlzHLznFN5aKbpRk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
